Repository jenkinsci/docker-plugin, pull requests merged in 2023-05, with the labels that each got.

#943 Modernize plugin
  .mvn/extensions.xml
  Jenkinsfile
  pom.xml
  src/main/java/io/jenkins/docker/connector/DockerComputerJNLPConnector.java
  src/test/java/io/jenkins/docker/connector/DockerComputerJNLPConnectorTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerNodeStepTest.java
Labels: internal

#946 Add `CODEOWNERS`
  .github/CODEOWNERS
Labels: skip-changelog

#944 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: internal

#945 Add Dependabot configuration
  .github/dependabot.yml
Labels: internal

#955 Miscellaneous code cleanup
  src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerContainerLabelKeys.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerContainerWatchdog.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerDisabled.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerManagement.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerSlave.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderControl.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderControlCloudOption.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderPublisher.java
  src/main/java/com/nirima/jenkins/plugins/docker/listener/DockerQueueListener.java
  src/main/java/com/nirima/jenkins/plugins/docker/publisher/DockerPublisherControl.java
  src/main/java/com/nirima/jenkins/plugins/docker/strategy/DockerOnceRetentionStrategy.java
  src/main/java/com/nirima/jenkins/plugins/docker/utils/JenkinsUtils.java
  src/main/java/com/nirima/jenkins/plugins/docker/utils/PortUtils.java
  src/main/java/io/jenkins/docker/DockerComputer.java
  src/main/java/io/jenkins/docker/DockerTransientNode.java
  src/main/java/io/jenkins/docker/FastNodeProvisionerStrategy.java
  src/main/java/io/jenkins/docker/client/DockerAPI.java
  src/main/java/io/jenkins/docker/client/DockerEnvUtils.java
  src/main/java/io/jenkins/docker/client/UsageTrackingCache.java
  src/main/java/io/jenkins/docker/connector/DockerComputerAttachConnector.java
  src/main/java/io/jenkins/docker/connector/DockerComputerConnector.java
  src/main/java/io/jenkins/docker/connector/DockerComputerJNLPConnector.java
  src/main/java/io/jenkins/docker/connector/DockerComputerSSHConnector.java
  src/main/java/io/jenkins/docker/pipeline/DockerNodeStep.java
  src/main/java/io/jenkins/docker/pipeline/DockerNodeStepExecution.java
  src/test/java/com/nirima/jenkins/plugins/docker/DockerCloudTest.java
  src/test/java/com/nirima/jenkins/plugins/docker/DockerImagePullStrategyTest.java
  src/test/java/com/nirima/jenkins/plugins/docker/DockerTemplateBaseTest.java
  src/test/java/com/nirima/jenkins/plugins/docker/DockerTemplateTest.java
  src/test/java/com/nirima/jenkins/plugins/docker/TestableDockerContainerWatchdog.java
  src/test/java/com/nirima/jenkins/plugins/docker/utils/JenkinsUtilsTest.java
  src/test/java/com/nirima/jenkins/plugins/docker/utils/PortUtilsTest.java
  src/test/java/io/jenkins/docker/client/DockerMultiplexedInputStreamTest.java
  src/test/java/io/jenkins/docker/client/UsageTrackingCacheTest.java
  src/test/java/io/jenkins/docker/connector/DockerComputerConnectorTest.java
  src/test/java/io/jenkins/docker/connector/DockerComputerJNLPConnectorTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerNodeStepTest.java
Labels: internal

#942 Docker plugin does not work correctly with agent Images built using BuildKit
  src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java
Labels: bug

#681 [JENKINS-48050] Declarative Pipeline support for dockerNode
  pom.xml
  src/main/java/io/jenkins/docker/pipeline/DockerAgent.java
  src/main/java/io/jenkins/docker/pipeline/DockerNodeStep.java
  src/main/java/io/jenkins/docker/pipeline/DockerNodeStepExecution.java
  src/main/resources/io/jenkins/docker/pipeline/DockerAgent/config.jelly
  src/main/resources/io/jenkins/docker/pipeline/DockerAgent/help-remoteFs.html
  src/main/resources/io/jenkins/docker/pipeline/DockerAgentScript.groovy
  src/test/java/io/jenkins/docker/pipeline/DockerAgentTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerNodeStepTest.java
Labels: enhancement

#959 Use `UncheckedIOException` where possible
  src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerManagementServer.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerSlave.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderControlOptionProvisionAndStart.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderControlOptionStart.java
  src/main/java/com/nirima/jenkins/plugins/docker/builder/DockerBuilderControlOptionStop.java
  src/main/java/io/jenkins/docker/client/DockerAPI.java
  src/test/java/com/nirima/jenkins/plugins/docker/utils/PortUtilsTest.java
Labels: internal

#960 Use updated environment variable
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-environmentsString.html
  src/test/java/io/jenkins/docker/connector/DockerComputerSSHConnectorTest.java
Labels: internal

#807 #712 Infer registry URL from Template image name
  src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java
  src/test/java/com/nirima/jenkins/plugins/docker/DockerCloudTest.java
Labels: enhancement

#797 Add support for Cloud Statistics plugin
  pom.xml
  src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java
  src/main/java/io/jenkins/docker/DockerComputer.java
  src/main/java/io/jenkins/docker/DockerTransientNode.java
Labels: feature

#961 Failed to capture container inspection data
  src/main/java/com/nirima/jenkins/plugins/docker/action/DockerBuildAction.java
Labels: bug

#964 Fix logic errors in `DockerMultiplexedInputStream`
  src/main/java/io/jenkins/docker/client/DockerMultiplexedInputStream.java
  src/test/java/io/jenkins/docker/client/DockerMultiplexedInputStreamTest.java
Labels: bug

#965 Remove invalid characters from README
  README.md
Labels: documentation

#966 Document how to use `jenkins/ssh-agent` Docker image
  README.md
Labels: documentation

#962 Prefer IPv4 localhost to IPv6 localhost
  src/main/java/io/jenkins/docker/connector/DockerComputerSSHConnector.java
  src/main/java/io/jenkins/docker/connector/HostPortComparator.java
  src/test/java/io/jenkins/docker/connector/HostPortComparatorTest.java
Labels: bug

#911 Update Docker logo to be a Jenkins symbol
  pom.xml
  src/main/java/com/nirima/jenkins/plugins/docker/DockerManagement.java
  src/main/java/com/nirima/jenkins/plugins/docker/action/DockerBuildAction.java
  src/main/java/com/nirima/jenkins/plugins/docker/action/DockerBuildImageAction.java
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildAction/index.jelly
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildAction/summary.jelly
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildImageAction/summary.jelly
  src/main/webapp/images/24x24/docker.png
  src/main/webapp/images/32x32/docker.png
  src/main/webapp/images/48x48/docker.png
Labels: feature

#967 Add sidebar to Docker build action
  src/main/java/com/nirima/jenkins/plugins/docker/action/DockerBuildAction.java
  src/main/java/com/nirima/jenkins/plugins/docker/action/DockerBuildImageAction.java
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildAction/index.jelly
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildImageAction/index.jelly
Labels: enhancement

#969 Clean up summaries
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildAction/summary.jelly
  src/main/resources/com/nirima/jenkins/plugins/docker/action/DockerBuildImageAction/summary.jelly
Labels: bug

#970 Remove unnecessary SpotBugs warning
  src/main/java/com/nirima/jenkins/plugins/docker/DockerRegistry.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerSlave.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java
  src/main/java/com/nirima/jenkins/plugins/docker/launcher/DockerComputerJNLPLauncher.java
  src/main/java/com/nirima/jenkins/plugins/docker/launcher/DockerComputerSSHLauncher.java
Labels: skip-changelog
