Repository jenkinsci/docker-plugin, pull requests merged in 2025-03, with the labels that each got.

#1134 Compatibility for old `DockerAgentScript`
  pom.xml
  src/main/java/io/jenkins/docker/pipeline/DockerAgent.java
  src/main/resources/io/jenkins/docker/pipeline/DockerAgentScript-old.groovy
Labels: bug

#1135 Use current hyperlinks in online help
  .gitattributes
  pom.xml
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-capabilitiesToAddString.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-capabilitiesToDropString.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-cpuPeriod.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-cpuQuota.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-cpuShares.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-cpus.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-dockerCommand.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-extraGroupsString.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-memoryLimit.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-securityOptsString.html
  src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplateBase/help-user.html
  src/main/resources/io/jenkins/docker/connector/DockerComputerSSHConnector/help-sshKeyStrategy.html
Labels: documentation

#1136 Enable continuous delivery
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: enhancement
