Repository jenkinsci/docker-plugin, pull requests merged in 2025-01, with the labels that each got.

#1124 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/com/nirima/jenkins/plugins/docker/DockerManagementServer.java
  src/main/java/com/nirima/jenkins/plugins/docker/DockerPluginConfiguration.java
  src/test/java/io/jenkins/docker/connector/DockerComputerConnectorTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerNodeStepTest.java
Labels: internal

#1125 Skip Docker-based tests when Docker is not available
  pom.xml
  src/test/java/io/jenkins/docker/connector/DockerComputerAttachConnectorTest.java
  src/test/java/io/jenkins/docker/connector/DockerComputerJNLPConnectorTest.java
  src/test/java/io/jenkins/docker/connector/DockerComputerSSHConnectorTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerAgentTest.java
  src/test/java/io/jenkins/docker/pipeline/DockerNodeStepTest.java
Labels: test

#1126 Place plugin configuration page in the 'System Configuration' section
  src/main/java/com/nirima/jenkins/plugins/docker/DockerManagement.java
Labels: enhancement
